### ISSUE TITLE
Way to set the appearance for the widget

### ISSUE THREAD

**Issue by santoshm** [instrumentl/rails-cloudflare-turnstile#131]
Hello,

The gem looks and works well and is really easy to integrate.

However, we'd like to use the Cloudflare Widget in `interaction-only` appearance mode as per https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/#appearance-modes. Does the gem support this setting, either via config or via an argument to the view helper?

Thanks,
Santosh

**Comment by Roguelazer** [comment]
Not right now, but that would be easy to add.

**Comment by Roguelazer** [comment]
This is now available in v0.2.1

**Comment by santoshm** [comment]
Excellent. Thanks!
