### ISSUE TITLE
Rails 8 support

### ISSUE THREAD

**Issue by MaNi4** [instrumentl/rails-cloudflare-turnstile#187]
Hello,

tried upgrade rails to 8. But got error `depends on rails >= 6.0, < 8`. Please, add support for rails 8.0.0.

Thanks.

**Comment by s01ipsist** [comment]
Will be fixed by https://github.com/instrumentl/rails-cloudflare-turnstile/pull/185

**Comment by matt17r** [comment]
For anyone else blocked until this gem is updated (released), you can upgrade to rails 8 while using this gem by pointing directly to the main branch on GitHub in your Gemfile:

```
gem "rails_cloudflare_turnstile", git: "https://github.com/instrumentl/rails-cloudflare-turnstile.git"
```

_Edit: Switched from `git@github.com...` to `https://github.com...` to fix issue with GitHub actions failing_
