### ISSUE TITLE
New release with Rails 7.1 support

### ISSUE THREAD

**Issue by AliOsm** [instrumentl/rails-cloudflare-turnstile#86]
I can see that Rails dependency is `gem "rails", ">= 6", "< 8"` in the `Gemfile`, while it is `spec.add_dependency "rails", ">= 5.0", "< 7.1"` in `rails-cloudflare-turnstile.gemspec`.

Do you have any plans to update the gemspec and release a new version? This blocks me from upgrading to Rails 7.1.

Thanks!

**Comment by AliOsm** [comment]
I opened a PR here: https://github.com/instrumentl/rails-cloudflare-turnstile/pull/87

**Comment by Roguelazer** [comment]
v0.1.6 is now on rubygems
